version: "3"
networks:
  dev-traefik-network:
    external:
      name: dev-traefik-network
services:
  dev-traefik:
    image: "traefik:v2.2.1"
    container_name: "dev-traefik"
    ports:
      - "80:80" # The HTTP port through which all http services can be accessed
      - "8080:8080" # The Web UI (enabled by --api.insecure=true)
      # - "5432:5432" # The postgres port
      # - "27017:27017" # The mongodb port
      # - "5672:5672" # The rabbitmq port
      # - "3306:3306" # The mysql port
      # - "9300:9300" # The elasticsearch port
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false" # If set to false, containers that don't have a traefik.enable=true label will be ignored from the resulting routing configuration.
      - "--entrypoints.web.address=:80"
      - "--entryPoints.web.forwardedHeaders.insecure"
      # - "--entrypoints.postgresql.address=:5432"
      # - "--entrypoints.mongodb.address=:27017"
      # - "--entrypoints.rabbitmq.address=:5672"
      # - "--entrypoints.mysql.address=:3306"
      # - "--entrypoints.elasticsearch.address=:9300"
      - '--tracing.serviceName=dev-traefik'
      - '--tracing.spanNameLimit=250'
      - '--tracing.zipkin=true'
      - '--tracing.zipkin.httpEndpoint=http://dev-openzipkin:9411/api/v2/spans'
      - '--tracing.zipkin.sameSpan=true'
      - '--tracing.zipkin.id128Bit=true'
      - '--tracing.zipkin.sampleRate=1'
      # - '--tracing.jaeger=true'
      # - '--tracing.jaeger.samplingServerURL=http://dev-jaeger:5778/sampling'
      # - '--tracing.jaeger.samplingType=const'
      # - '--tracing.jaeger.samplingParam=1'
      # - '--tracing.jaeger.localAgentHostPort=127.0.0.1:6831'
      # - '--tracing.jaeger.gen128Bit'
      # - '--tracing.jaeger.propagation=jaeger'
      # - '--tracing.jaeger.traceContextHeaderName=uber-trace-id'
      # - '--tracing.jaeger.collector.endpoint=http://dev-jaeger:14268/api/traces?format=jaeger.thrift'
      # - '--tracing.jaeger.collector.user=my-user'
      # - '--tracing.jaeger.collector.password=my-password'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev-traefik-network"
      - "traefik.http.routers.dev-traefik.entrypoints=web"
      - "traefik.http.routers.dev-traefik.rule=Host(`traefik.localhost`)"
      - "traefik.http.services.dev-traefik.loadbalancer.server.port=8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - dev-traefik-network
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
