version: "3"
services:
  dev-rabbit:
    image: "rabbitmq:3.8.5-management"
    container_name: dev-rabbit
    expose:
      - 15672
      - 5672
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev-traefik-network"
      - "traefik.http.routers.dev-rabbit.entrypoints=web"
      - "traefik.http.routers.dev-rabbit.rule=Host(`rabbit.localhost`)"
      - "traefik.http.services.dev-rabbit.loadbalancer.server.port=15672"
    hostname: "dev-rabbit"
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 1024MiB
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - "$DEV_CONTAINERS_HOME/dev-rabbit:/var/lib/rabbitmq"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
