version: "3"
services:
  dev-rabbit:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev-traefik-network"
      - "traefik.http.routers.dev-rabbit.entrypoints=web"
      - "traefik.http.routers.dev-rabbit.rule=Host(`rabbit.localhost`)"
      - "traefik.http.services.dev-rabbit.loadbalancer.server.port=15672"
    networks:
      - dev-traefik-network
    depends_on:
      - dev-traefik
