version: "3"
services:
  dev-consul:
    image: "consul:1.8.0"
    container_name: dev-consul
    expose:
      - 8300
      - 8600
      - 8500
    ports:
      - "8300:8300"
      - "8600:8600"
      - "8500:8500"
    command: "agent -dev -ui -client=0.0.0.0"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"