version: '3'
services:
  dev-consul:
    image: "consul:1.6.0"
    container_name: dev-consul
    expose:
      - 8300
      - 8600
      - 8500
    ports:
      - "8300:8300"
      - "8600:8600"
      - "8500:8500"
    command: "agent -dev -ui"
    network_mode: "host"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  dev-postgres:
    image: "postgres:11"
    container_name: dev-postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    network_mode: "host"
    environment: 
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - "$DEV_CONTAINERS_HOME/dev-postgres:/var/lib/postgresql/data"
    command: "postgres -c log_statement=all -c log_duration=on -c log_min_duration_statement=-1"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
  dev-mongo:
    image: "mongo:4.2.0"
    container_name: dev-mongo
    expose:
    - 27017
    ports:
    - "27017:27017"
    network_mode: "host"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "$DEV_CONTAINERS_HOME/dev-mongo:/data/db"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"