version: "3"
services:
  dev-keycloak:
    image: "jboss/keycloak:10.0.0"
    container_name: dev-keycloak
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev-traefik-network"
      - "traefik.http.routers.dev-keycloak.entrypoints=web"
      - "traefik.http.routers.dev-keycloak.rule=Host(`keycloak.localhost`)"
      - "traefik.http.services.dev-keycloak.loadbalancer.server.port=8080"
    environment: # why this address https://stackoverflow.com/questions/54763936/communication-between-microservices-with-docker-compose-and-traefik
      # - "PROXY_ADDRESS_FORWARDING=true"
      DB_VENDOR: POSTGRES
      DB_ADDR: dev-postgres
      DB_DATABASE: dev_keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    networks:
      - dev-traefik-network
    depends_on: 
      - dev-traefik
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
