version: "3"
services:
  dev-postgres:
    image: "postgres:12.2"
    container_name: dev-postgres
    expose:
      - 5432
    command: "postgres -c log_statement=all -c log_duration=on -c log_min_duration_statement=-1"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dev-traefik-network"
      - "traefik.tcp.routers.dev-postgres.entrypoints=postgresql"
      - "traefik.tcp.routers.dev-postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.services.dev-postgres.loadbalancer.server.port=5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    volumes:
      - "$DEV_CONTAINERS_HOME/dev-postgres:/var/lib/postgresql/data"
    networks:
      - dev-traefik-network
    depends_on:
      - dev-traefik
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
