version: "3.4"
services:
  dev-kibana:
    # Apparently the version of kibana is dependent on the version of elasticsearch
    image: "kibana:7.8.0"
    container_name: dev-kibana
    expose:
      - 5601
    ports:
      - 5601:5601
    environment: # why this address https://stackoverflow.com/questions/54763936/communication-between-microservices-with-docker-compose-and-traefik
      ELASTICSEARCH_HOSTS: http://dev-elasticsearch:9200/
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
