version: "3"
services:
  dev-mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: dev-mailhog
    expose:
      - 1025
      - 8025
    ports:
      - 1025:1025
      - 8025:8025
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"