version: "3.4"
services:
  dev-mysql:
    image: "mysql:8.0.20"
    container_name: dev-mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_user
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "$DEV_CONTAINERS_HOME/dev-mysql:/var/lib/mysql"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
