version: "3.4"
services:
  dev-mongo:
    image: "mongo:4.2.8"
    container_name: dev-mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "$DEV_CONTAINERS_HOME/dev-mongo:/data/db"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"