version: "3.4"
services:
  dev-openzipkin:
    labels:
      traefik.enable: "true"
      traefik.docker.network: "dev-net-traefik"
      traefik.http.routers.dev-openzipkin.entrypoints: "web"
      traefik.http.routers.dev-openzipkin.rule: "Host(`zipkin.localhost`)"
      traefik.http.services.dev-openzipkin.loadbalancer.server.port: "9411"
    networks:
      - dev-net-traefik
    depends_on:
      - dev-traefik
